#!/usr/bin/python3
import sys


def factorize_number(number):
    factors = []
    for i in range(2, int(number ** 0.5) + 1):
        if number % i == 0:
            factors.append((i, number // i))
            break
    return factors


def factorize_file(filename):
    with open(filename, 'r') as file:
        for line in file:
            number = int(line.strip())
            factors = factorize_number(number)
            for factor in factors:
                print(f"{number}={factor[1]}*{factor[0]}")


def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
    else:
        factorize_file(sys.argv[1])


if __name__ == '__main__':
    main()
